### ISSUE TITLE
cannot get running

### ISSUE THREAD

**Issue by linhowie** [pranit123/Twitter-Clone#3]
root@couchapps Twitter-Clone]# npm install -D json-server
npm WARN react-native-branch@2.0.0-beta.3 requires a peer of react@>=15.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-gesture-handler@1.0.0-alpha.22 requires a peer of react@> 15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-svg@5.5.1 requires a peer of react-native@>=0.50.0 but none is installed. You must install peer dependencies yourself.
npm WARN twitter-clone@0.1.0 No repository field.
npm WARN twitter-clone@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by linhowie** [comment]
I am just trying to get the server started

**Comment by pranit123** [comment]
You must install json-server globally. 
Run `npm install -g json-server`
