### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by redefinered** [pranit123/Twitter-Clone#4]
I tried to follow the instructions on installation but it didn't work. I think packages are outdated and not compatible with each other. I'm on a Windows.

**Comment by pranit123** [comment]
Can you quote the exact error you got?

**Comment by OpenBrazil** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.1 (node_modules\react-native\node_modules\jest-haste-map\node_modules\sane\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.1 (node_modules\sane\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN react-native-svg@5.3.0 requires a peer of react@16.0.0-alpha.12 but none was installed.
npm WARN react-native@0.48.4 requires a peer of react@16.0.0-alpha.12 but none was installed.
npm WARN react-native-svg@5.5.1 requires a peer of react-native@>=0.50.0 but none was installed.
npm WARN twitter-clone@0.1.0 No repository field.
npm WARN twitter-clone@0.1.0 No license field.

**Comment by OpenBrazil** [comment]
and running npm install --no-optional

only these warnings:

npm WARN react-native-svg@5.3.0 requires a peer of react@16.0.0-alpha.12 but none was installed.
npm WARN react-native@0.48.4 requires a peer of react@16.0.0-alpha.12 but none was installed.
npm WARN react-native-svg@5.5.1 requires a peer of react-native@>=0.50.0 but none was installed.
npm WARN twitter-clone@0.1.0 No repository field.
npm WARN twitter-clone@0.1.0 No license field.

**Comment by pranit123** [comment]
These are warnings in the packages, not errors. You can ignore them everything should work fine

**Comment by fredfortier** [comment]
Here is the error which I get.
<img width="423" alt="screenshot 2018-03-10 22 57 26" src="https://user-images.githubusercontent.com/1474114/37249487-75ed3bba-24b6-11e8-8d2a-f47888a53c13.png">

**Comment by OpenBrazil** [comment]
06:56:51: Warning: 'react-native' peer depencency missing. Run `npm ls` in C:\dev\sand\reactnative\Twitter-Clone to see full warning.

If there is an issue running your project, please run `npm install` in C:\dev\sand\reactnative\Twitter-Clone and restart.

06:59:47: Failed building JavaScript bundle

**Comment by OpenBrazil** [comment]
![image](https://user-images.githubusercontent.com/9018096/37396052-90eec850-2756-11e8-9c86-cbadf483bdb3.png)

**Comment by Asfandtnt** [comment]
@OpenBrazil were you able to resolve the issue ? i am getting same issue

**Comment by Asfandtnt** [comment]
this is how to solve it

npm uninstall @expo/vector-icons --save

and then

npm install @expo/vector-icons --save

**Comment by Asfandtnt** [comment]
If you are unable to build twitter application Then use following Commands
npm uninstall @expo/vector-icons --save
 
npm install @expo/vector-icons --save


and after that if you are unable to login it then do following steps
npm uninstall axios --save
npm install axios --save

and in sagas.js file change ip adderss against each function
