### ISSUE TITLE
Problem logging in

### ISSUE THREAD

**Issue by dhazlettjr** [pranit123/Twitter-Clone#6]
I cannot sign up with a new user and I also cannot login in with the username and pass provided from the json file.

**Comment by theankurkedia** [comment]
This app is not using a real server and fake data is being served. Hence you cannot signup and to use login credentials, you need to start the server by running ```ssh $npm run serve```

**Comment by moiscye** [comment]
> I cannot sign up with a new user and I also cannot login in with the username and pass provided from the json file.

Hi, Did you ever get it to fetch the data and actually log in?
