### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by fislMON** [pranit123/Twitter-Clone#8]
this comes infinitely :
20:24:42: ::ffff:127.0.0.1 - - [27/May/2018:17:24:42 +0000] "GET /debug HTTP/1.1" 404 144 "-" "-"

**Comment by pranit123** [comment]
Did you start the json-server?

**Comment by fislMON** [comment]
yes ..
npm install -g json-server

**Comment by octoliang** [comment]
> Loading generate.js
> Done
> 
> Resources
> http://localhost:3000/tweets
> http://localhost:3000/userTweets
> http://localhost:3000/login
> http://localhost:3000/tweetReplies
> 
> Home
> http://localhost:3000
> 
> Type s + enter at any time to create a snapshot of the database



> this comes infinitely :
> 20:24:42: ::ffff:127.0.0.1 - - [27/May/2018:17:24:42 +0000] "GET /debug HTTP/1.1" 404 144 "-" "-"

I also encountered this problem, have you solved it
