### ISSUE TITLE
Uncaught Error: 21.0.0 is not a valid SDK version

### ISSUE THREAD

**Issue by mcandrak** [pranit123/Twitter-Clone#9]
how i can solve this ?
![whatsapp image 2018-07-05 at 08 28 45](https://user-images.githubusercontent.com/25250310/42298004-9848c058-802d-11e8-993d-0ff5f93f95b4.jpeg)

**Comment by itsmrob** [comment]
I got the same error,  can anyone help me?

**Comment by nadysaptra** [comment]
you should 
- uninstall expo on device
- remove node_modules
- npm instal
- npm start

**Comment by fathurhidayat3** [comment]
I'm able to fix this by changing sdkVersion in app.json file from version 21 to 32 then update expo dependency in package.json to version 32 too. After that run npm install. In case you encounter another issue, here I put some solution : 

- Unable to resolve module 'scheduler/tracing' : 
Solution : Change react version to "16.6.0-alpha.8af6728"
Reference : https://github.com/facebook/react-native/issues/21783

- Unable to resolve AntDesign in IconNB.js :
Solution : npm install @expo/vector-icons@^9.0.0
Reference : https://github.com/expo/vector-icons/issues/58

- Cannot read property 'filename' of undefined at PluginPass.JSXOpeningElement : 
Solution : change .babelrc file config to { "presets": ["react-native"] }
Reference : https://stackoverflow.com/questions/51765313/react-native-v0-56-cannot-read-property-filename-of-undefined-at-pluginpass-j

- [SDK32] undefined is not an object (evaluating '_expo2.default.KeepAwake') : 
Solution : follow step shown by expo in terminal when you run npm start
Reference : https://github.com/expo/expo/issues/3152

Hope it helps
